name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

    steps:
      - name: Pull Docker image
        run: sudo docker pull "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest"

      - name: Delete Old docker container
        run: |
          sudo docker rm -f "sih_isro-container" || true
          sudo docker network inspect "sih_isro" >/dev/null 2>&1 || sudo docker network create "sih_isro"

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            --name "sih_isro-container" \
            --network "sih_isro" \
            -p 8000:8000 \
            "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest"