name: CI Pipeline

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t $DOCKER_IMAGE_NAME .
    
    - name: Push to Docker Hub
      run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

